name: grid_wars
description: "A new Flutter game project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  top_snackbar_flutter: ^3.3.0
  vibration: ^3.1.4
  mask_text_input_formatter: ^2.9.0
  animate_do: ^4.2.0
  skeletonizer: ^1.4.3
  flutter_spinkit: ^5.2.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  formz: ^0.8.0
  equatable: ^2.0.7
  intl: ^0.20.2
  flutter_svg: ^2.0.17
  go_router: ^14.8.1
  flutter_markdown: ^0.7.7
  shared_preferences: ^2.2.2
  get_it: ^8.0.3
  another_flushbar: ^1.12.30
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  intl_utils: ^2.8.4
  build_runner: ^2.4.6


flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/exo/Exo-Thin.ttf
          weight: 100
        - asset: assets/fonts/exo/Exo-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/exo/Exo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/exo/Exo-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/exo/Exo-Light.ttf
          weight: 300
        - asset: assets/fonts/exo/Exo-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/exo/Exo-Regular.ttf
          weight: 400
        - asset: assets/fonts/exo/Exo-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/exo/Exo-Medium.ttf
          weight: 500
        - asset: assets/fonts/exo/Exo-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/exo/Exo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/exo/Exo-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/exo/Exo-Bold.ttf
          weight: 700
        - asset: assets/fonts/exo/Exo-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/exo/Exo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/exo/Exo-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/exo/Exo-Black.ttf
          weight: 900
        - asset: assets/fonts/exo/Exo-BlackItalic.ttf
          weight: 900
          style: italic